# Data: cpu/mem
# Filter: metadata-exchange and stats filters
# VM mode: nullvm
telemetry_mode: "v2-stats-nullvm"
conn:
    - 16
qps:
    - 10
    - 100
    - 200
    - 400
    - 800
    - 1000
duration: 240
perf_record: true
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

extra_labels: "security_peer_authn"

jitter: true
