# Data: cpu/mem
# Filter: metadata-exchange and stackdriver filters with logging off
# VM mode: nullvm
telemetry_mode: "v2-sd-nologging-nullvm"
conn:
    - 16
qps:
    - 10
    - 100
    - 500
    - 1000
    - 2000
    - 3000
duration: 240
metrics:
    - cpu
    - mem
perf_record: true
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: false

jitter: true
