# Data: latency
# Filter: metadata-exchange and stackdriver filters with logging off
# VM mode: nullvm
telemetry_mode: "v2-sd-nologging-nullvm"
conn:
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
qps:
    - 1000
duration: 240
metrics:
    - p50
    - p90
    - p99
perf_record: false
run_bothsidecar: true
run_serversidecar: true
run_clientsidecar: false
run_baseline: false
