apiVersion: v1
name: alertmanager
version: '1.0.0'
description: Helm chart for configuring alertmanager
keywords:
  - istio
  - alertmanager
sources:
  - http://github.com/istio/istio
icon: https://istio.io/favicons/android-192x192.png
