fortioImage: fortio/fortio:latest
pilotImage: gcr.io/istio-release/pilot:release-1.1-latest-daily
kubectlImage: gcr.io/istio-release/kubectl:release-1.1-latest-daily
proxyImage: gcr.io/istio-release/proxyv2:release-1.1-latest-daily
nodeAgentImage: gcr.io/istio-release/node-agent-k8s:release-1.1-latest-daily
certManagerImage: quay.io/jetstack/cert-manager-controller:v0.6.2

numOfClientConns: 10
numOfClientQps: 100
clientConnTimeoutDuration: 15s

namespace: test
