# This is used to generate istio.yaml for a stress/load test cluster.

global:
  telemetryNamespace: istio-telemetry
  configNamespace: istio-control
  istioNamespace: istio-system
  policyNamespace: istio-policy

  imagePullPolicy: Always
  refreshInterval: 30s
  k8sIngressSelector: ingressgateway

  controlPlaneSecurityEnabled: false

  meshExpansion:
    enabled: true
    useILB: true

  proxy:
    enableCoreDump: true
    concurrency: 2
    accessLogFile: ""

    envoyAccessLogService:
      enabled: false
      host: accesslog-grpc.istio-system.svc.cluster.local
      port: 18090

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  multiCluster:
    enabled: true

    # Provides dns resolution for global services
  podDNSSearchNamespaces:
    - global
    - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"
  sds:
    enabled: true
    udsPath: "unix:/var/run/sds/uds_path"
    useNormalJwt: true

gateways:
  istio-ilbgateway:
    enabled: true

  istio-ingressgateway:
    enabled: true
    secretVolumes:
      - name: istio-ingressgateway-certs
        secretName: istio-ingressgateway-certs
        mountPath: /etc/istio/ingressgateway-certs
      - name: istio-ingressgateway-certs-fortiotls
        secretName: istio-ingressgateway-certs-fortiotls
        mountPath: /etc/istio/ingressgateway-certs-fortiotls
      - name: istio-ingressgateway-certs-fortionoistio
        secretName: istio-ingressgateway-certs-fortionoistio
        mountPath: /etc/istio/ingressgateway-certs-fortionoistio
    labels:
      istio: ingressgateway
      ver: ingress10
      app: istio-ingressgateway
      name: gateway
    type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
    ports:
      - port: 80
        targetPort: 80
        name: http2
        nodePort: 31380
      - port: 443
        name: https
        nodePort: 31390
      - port: 31400
        name: tcp
      - port: 5201
        name: tcp-iperf-cont
      - port: 5202
        name: tcp-iperfraw
      - port: 5203
        name: tcp-iperf
      - port: 5204
        name: tcp-iperf-tls

pilot:
  env:
    PILOT_PUSH_THROTTLE: 50
    GODEBUG: gctrace=1

ingress:
  enabled: false

sidecarInjectorWebhook:
  enabled: true

grafana:
  enabled: true
  prometheusNamespace: istio-prometheus
   datasources:
     datasources.yaml:
       apiVersion: 1
       datasources:
         - name: Prometheus
           type: prometheus
           orgId: 1
           url: http://istio-prometheus.istio-prometheus:9090
           access: proxy
           # isDefault: true
           jsonData:
             timeInterval: 5s
           editable: true

mixer:
  telemetry:
    enabled: true
    replicaCount: 1
    cpu:
      targetAverageUtilization: 80
    sessionAffinityEnabled: false


tracing:
  enabled: true
  jaeger:
    enabled: true

servicegraph:
  enabled: false

prometheus:
  createPrometheusResource: true
  createKubeletMonitor: true
  enabled: false

kiali:
  enabled: false
  tag: latest

certmanager:
  enabled: false
  email: mjog@google.com
  commonName: ingress.v10.istio.webinf.info
  certificates:
    - "ingress.v10.istio.webinf.info"
  #commonName: fortiotls.v10.istio.webinf.info
  #certificates:
  #  - "fortiotls.v10.istio.webinf.info"


nodeagent:
  enabled: false
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true
    SECRET_GRACE_DURATION: "30m"
    SECRET_JOB_RUN_INTERVAL: "30s"
    SECRET_TTL: "1h"
