global:
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: true

  sds:
    enabled: false
    udsPath: ""
    useNormalJwt: false

gateways:
  istio-ingressgateway:
    sds:
      enabled: false

security:
  # Short lived cert to test rotation.
  workloadCertTtl: 30m

nodeagent:
  enabled: false
  image: node-agent-k8s
  env:
    CA_PROVIDER: "Citadel"
    CA_ADDR: "istio-citadel:8060"
    VALID_TOKEN: true