version: 2

jobs:
  build_turned_off_for_now:
    working_directory: /workspace/go/src/istio.io/tools
    docker:
      # Image with KIND installed, based on Istio Kind node-image
      # Should have all tools we need, recreated when we rev the tool versions.
      - image: istionightly/kind:latest
        environment:
          GOPATH: /workspace/go
          SKIP_CLEANUP: 1

    # Can run multiple images, first is primary, all use localhost
    steps:
      - checkout
      - setup_remote_docker: {}
      # Only on paid version
      #    docker_layer_caching: true
      - run:
          command: |
            mkdir -p $GOPATH/src/istio.io
            git clone https://github.com/istio/istio.git $GOPATH/src/istio.io/istio
            git clone https://github.com/istio/installer.git $GOPATH/src/istio.io/installer
      - run:
          command: make test
      - run:
          when: always
          command: (cd $GOPATH/src/istio.io/installer; make kind-logs)
      - store_test_results:
          path: /workspace/go/out/tests
      - store_artifacts:
          path: /workspace/go/out/logs

  build:
    docker:
      - image: gcr.io/istio-testing/circleci:2019-06-13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/istio.io/tools
    steps:
      - checkout
      - run:
          name: Building
          command: go build ./...

  lint:
    docker:
      - image: gcr.io/istio-testing/circleci:2019-06-13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/istio.io/tools
    steps:
      - checkout
      - run:
          name: Linting
          command: make lint

  test:
    docker:
      - image: gcr.io/istio-testing/circleci:2019-06-13
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/istio.io/tools
    steps:
      - checkout
      - run:
          name: Running unit tests
          command: go test -race ./...

  fmtpy:
    docker:
      - image: gcr.io/istio-testing/circleci:2019-06-13
    working_directory: /go/src/istio.io/tools
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: fmtpy
          command: make fmtpy-checkonly

workflows:
  version: 2
  nightly:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
                 - dev
    jobs:
      - build

  all:
    jobs:
      - build
      - lint
      - test
