apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: entrypoint-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.serviceNamePrefix }}0.local
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: entrypoint
spec:
  gateways:
  - entrypoint-gateway
  hosts:
  - {{ .Values.serviceNamePrefix }}0.local
  http:
  - route:
    - destination:
        host: {{ .Values.serviceNamePrefix }}0
        subset: all
        port:
          number: 8080
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.serviceNamePrefix }}0
spec:
  host: {{ .Values.serviceNamePrefix }}0
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: all
    labels:
      app: {{ .Values.serviceNamePrefix }}0
  - name: v1
    labels:
      app: {{ .Values.serviceNamePrefix }}0
      version: v1
  - name: v2
    labels:
      app: {{ .Values.serviceNamePrefix }}0
      version: v2
