# Configuration Set5: CPU and memory with telemetryv2 using NullVM.
telemetry_mode: "v2-nullvm"
conn:
    - 16
qps:
    - 10
    - 100
    - 500
    - 1000
    - 2000
    - 3000
duration: 240
metrics:
    - cpu
    - mem
perf_record: false
run_serversidecar: true
run_baseline: true