load_gen_type: ${LOAD_GEN_TYPE}
telemetry_mode: "dryrun"
conn:
  - 8
qps:
  - 1000
duration: 100
metrics:
  - p50
  - p90
  - p99
perf_record: false
run_bothsidecar: true
run_serversidecar: false
run_clientsidecar: false
run_baseline: true